### PR TITLE
feat: Add inner_block slot support pass as HTML

### PR DESCRIPTION
**Pull request by ci**
👋 @mrdotb - not sure if you wanna go this route, but I found this useful in my project, I've added some basic slot interop with react where we can pass the inner_block as `{ children }` to the component, though it happens as HTML so providers etc won't work with nested react components (pretty similar to how live_vue does it)

# Contributor checklist

- [x] My commit messages follow the [Conventional Commit Message Format](https://gist.github.com/stephenparish/9941e89d80e2bc58a153#format-of-the-commit-message)
      For example: `fix: Multiply by appropriate coefficient`, or
      `feat(Calculator): Correctly preserve history`
      Any explanation or long form information in your commit message should be
      in a separate paragraph, separated by a blank line from the primary message

### CODE REVIEW

**Comment by ci** [comment]
thanks, and yep tested with SSR, and with both vite / nodejs. I'll take a look at adding an example too!

**Comment by mrdotb** [comment]
:wave: I had a deeper look in the code and it's good :+1:  but before merging I would like an example in the demo.
I just added a new example for hybrid form today if you want to have a look https://github.com/mrdotb/live_react/commit/94b33d24df32f42326f0e14bb3e9ce5cef8db509

**Comment by mrdotb** [comment]
I added an example and merged it in https://github.com/mrdotb/live_react/pull/21

**Comment by ci** [comment]
awesome, thank you! sorry I didn't get a chance to add the example in the meantime

**Pull request closed without merging**
