### PR TITLE
feat(vitejs)!: switch from Mix Esbuild to Vite.js

### PR DESCRIPTION
**Pull request by mrdotb**
The development experience with Mix Esbuild, especially when enabling SSR, has not been smooth due to several issues:
- Mismatch between React SSR components and client components, caused by timing issues
- Inability to silence logs for the Esbuild server
- Difficulty in tweaking the Esbuild config

The options were either to use a custom Esbuild config, which would involve removing Mix Esbuild, or to switch to Vite.js.

I chose Vite.js over a custom Esbuild setup because the integration with React SSR is better documented. Additionally, with Vite.js, I no longer need to ship an NPM package for `live_react`, which also simplifies work on `live_react` itself.

## TODO
- [x] Update documentation
- [x] Mix task to setup live react

### CODE REVIEW

**Comment by 27medkamal** [comment]
First of all, love what you're doing with live_react

Minor comment, in regards to not having to ship an npm package, have you considered shipping the js along with the hex package similar to how phoenix does it internally? This was the motivation behind my PR #13

**Comment by mrdotb** [comment]
:wave: 

There is probably an equivalent in vitejs :thinking:  but I does not look like a good idea for me it make the js deps hard to pinpoint.
For stock phoenix it make sense since they don't ship a package.json by default and use a vendor instead.

When looking at the package.json post vitejs it's easy to understand what deps are coming from hex.
https://github.com/mrdotb/live_react/blob/feat/vitejs/live_react_examples/assets/package.json#L22

**Comment by Valian** [comment]
Good work on that issue! 

Personally I love Vite. Wondering if we could maybe create a hex package working in a same way as tailwind / esbuild, but automatically using vite under the hood. It's a waste to implement that integration over and over again.

One issue left with Vite is with hashing files. Vite does it on it's own and it conflicts with hashing of phoenix. So it's impossible to use both and it's a problem when using lazy components. So for now it's best to keep it disabled.

**Comment by 27medkamal** [comment]
I like this. Keen to try it. Keep up the good work 💪

> When looking at the package.json post vitejs it's easy to understand what deps are coming from hex. https://github.com/mrdotb/live_react/blob/feat/vitejs/live_react_examples/assets/package.json#L22

**Comment by mrdotb** [comment]
It seems to be a thing for laravel https://laravel.com/docs/11.x/vite and in ruby/rails https://vite-ruby.netlify.app/
so it should be possible to do an equivalent for phoenix but It need more investigation :thinking:

**Comment by Valian** [comment]
Vite is the best 💚💜 😍

**Pull request merged**
