### PR TITLE
Fix vite config

### PR DESCRIPTION
**Pull request by 27medkamal**
This wasn't obvious to me at first as the new vite installation guide works on the examples provided here.

However, there is an issue where if you use `React.forwardRef` in your components, you get the error:
```Uncaught TypeError: React.forwardRef is not a function```

It seems that live_vue has the same config as well
https://github.com/Valian/live_vue/blob/main/assets/copy/vite.config.js#L22

As for why it works otherwise without having this line, I'm not entirely sure, but going by live_vue which this vite implementation models, it seems to fix the issue.

# Contributor checklist

- [x] My commit messages follow the [Conventional Commit Message Format](https://gist.github.com/stephenparish/9941e89d80e2bc58a153#format-of-the-commit-message)
      For example: `fix: Multiply by appropriate coefficient`, or
      `feat(Calculator): Correctly preserve history`
      Any explanation or long form information in your commit message should be
      in a separate paragraph, separated by a blank line from the primary message

### CODE REVIEW

**Comment by 27medkamal** [comment]
Actually, this seems to break SSR. Will have to investigate more

**Comment by mrdotb** [comment]
Hello, I was going to say that I try this but it break SSR.
Could you push add an example with forward ref ?

**Comment by mrdotb** [comment]
I try a simple forwardRef, useRef but I don't see any issue :thinking: 
```javascript
import React, { forwardRef, useRef } from 'react';

// Child component using forwardRef
const Input = forwardRef((props, ref) => {
  return <input ref={ref} {...props} />;
});

export function Simple() {
  const inputRef = useRef(null);

  const focusInput = () => {
    // This will focus the input in the child component
    inputRef.current.focus();
  };

  return (
    <div>
      <Input ref={inputRef} placeholder="Type something here..." />
      <button onClick={focusInput}>Focus Input</button>
    </div>
  );
}
```

**Comment by 27medkamal** [comment]
I also tried adding it to your examples project, but it worked fine.

I'll need to debug this a bit more

**Comment by 27medkamal** [comment]
This ended up working just fine on my end after cleaning up deps and node_modules. Not sure what happened there, so closing this for now. Sorry for the false alarm.

**Comment by timadevelop** [comment]
For anyone having the same issue: try to rename `react` folder to something like `react-components` & update imports and vite/ts configs to use the new folder.

@mrdotb I had the same issue in one of the projects and I believe it's because of the "react" folder in this particular case. I did not investigate further & I'm not sure what is the exact reason, maybe Vite has some issues with aliases, but in my case renaming the folder worked.

btw, it might be worth changing the `react` folder to something else, not only because of this problem, but also because of semantics.

**Comment by mrdotb** [comment]
#19 fixed

**Pull request closed without merging**
